version: '3.8'

services:
  nomic-embed-text:
    image: ilopezluna / nomic-embed-text
    container_name: nomic_embed_text
    ports:
      - "8001:8001" # Adjust the ports as needed
    environment:
      - MODEL_SERVER_PORT=8001 # Ensure the model listens on this port
    restart: always

  llama3.2:
    image: alpine / llama3.2
    container_name: llama32
    ports:
      - "8002:8002" # Adjust the ports as needed
    environment:
      - MODEL_SERVER_PORT=8002 # Ensure the model listens on this port
    restart: always

  app:
    image: <your-public-docker-image>:<tag> # Replace with your public Docker image and tag
    container_name: my_render_app
    ports:
      - "8080:8080" # Adjust the app's exposed port as needed
    depends_on:
      - nomic-embed-text
      - llama3.2
    environment:
      - NOMIC_EMBED_URL=http://nomic-embed-text:8001
      - LLAMA32_URL=http://llama3.2:8002
    restart: always
